resource:
  path: "/com/example/infinity/"
  fxml: "/com/example/infinity/fxml/"
  image: "/com/example/infinity/icons/"
  audio: "/com/example/infinity/audio/"

audio:
  max_retry_counts: 3
  main_menu_sounds_names:
    - "MainTheme-1.mp3"